import { z } from 'zod'
import { generateObject } from 'ai'
import { createAnthropic } from '@ai-sdk/anthropic'
import { ReviewError } from './index.js'

export interface RepoFileSample {
  path: string
  content: string
}

const GeneratedProfileSchema = z.object({
  profile: z.string().describe("Built-in profile: 'typescript', 'laravel', 'vue', or 'laravel-vue'"),
  language: z.string().describe("ISO language code for review comments, e.g. 'en' or 'th'"),
  rules: z.array(z.object({
    id: z.string().describe('Kebab-case rule identifier'),
    severity: z.enum(['bug', 'suggestion', 'nitpick', 'praise']),
    message: z.string().describe('Short rule description shown in review comment'),
  })).describe('Custom rules detected from the codebase patterns'),
  ignore: z.array(z.string()).describe('Glob patterns for files to skip'),
  limits: z.object({
    max_file_size_lines: z.number().min(100).max(2000),
    max_files_per_pr: z.number().min(5).max(50),
  }),
  reasoning: z.string().describe('Brief explanation of why these rules were chosen'),
})

export type GeneratedProfile = z.infer<typeof GeneratedProfileSchema>

/**
 * Analyze a sample of repository files and generate a tailored .reviewbot.yml config.
 * Returns both the structured profile and the YAML string.
 */
export async function generateConventionProfile(
  files: RepoFileSample[],
  repoFullName: string,
): Promise<{ profile: GeneratedProfile; yaml: string }> {
  const fileSummary = files
    .slice(0, 20) // cap tokens
    .map((f) => `### ${f.path}\n\`\`\`\n${f.content.slice(0, 800)}\n\`\`\``)
    .join('\n\n')

  try {
    const anthropic = createAnthropic()
    const { object } = await generateObject({
      model: anthropic(process.env.ANTHROPIC_MODEL ?? 'claude-sonnet-4-6'),
      schema: GeneratedProfileSchema,
      system: `You are an expert code convention analyzer.
Analyze the provided code samples from the repository "${repoFullName}" and generate a .reviewbot.yml configuration.

Detect:
- Primary framework/language (Laravel, Vue.js, TypeScript, React, etc.)
- Common anti-patterns visible in the code
- Files or directories that should be ignored in reviews (migrations, generated code, tests)
- Appropriate review scope limits based on apparent project size

Output practical, actionable rules that match the patterns you actually see in the code.
Keep rules focused on issues that would cause real problems, not style preferences.`,
      prompt: `Repository: ${repoFullName}\n\nFile samples:\n\n${fileSummary}`,
    })

    const yaml = buildYaml(object)
    return { profile: object, yaml }
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error)
    const statusCode = (error as { statusCode?: number; status?: number }).statusCode
      ?? (error as { statusCode?: number; status?: number }).status

    if (statusCode === 429 || (statusCode && statusCode >= 500)) {
      throw new ReviewError(`Claude API error during profile generation: ${message}`, true, error)
    }
    throw new ReviewError(`Profile generation failed: ${message}`, false, error)
  }
}

function buildYaml(p: GeneratedProfile): string {
  const rulesYaml = p.rules.length > 0
    ? `\nrules:\n${p.rules.map((r) =>
        `  - id: ${r.id}\n    severity: ${r.severity}\n    message: "${r.message.replace(/"/g, '\\"')}"`
      ).join('\n')}`
    : '\nrules: []'

  const ignoreYaml = p.ignore.length > 0
    ? `\nignore:\n${p.ignore.map((i) => `  - "${i}"`).join('\n')}`
    : '\nignore: []'

  return `# Generated by AI Review Bot — ${new Date().toISOString().slice(0, 10)}
# Customize this file to match your team conventions.
version: 1
profile: ${p.profile}
language: ${p.language}
${rulesYaml}
${ignoreYaml}

limits:
  max_file_size_lines: ${p.limits.max_file_size_lines}
  max_files_per_pr: ${p.limits.max_files_per_pr}
`
}
